### ISSUE TITLE
Support for environment variables

### ISSUE THREAD

**Issue by hsz** [iliasbhal/serverless-static#2]
There is no support for environment variables at all. When I try to set i.e. bucket name with:

```
custom:
  static:
    path: ./public
    deploy: true
    bucket: ${env:BUCKET_NAME}
```

settings provided for `_sync.js` still uses `${env:BUCKET_NAME}` as a value.
